"""
app.py — Sales Forecasting & Demand Intelligence Dashboard
Task 7, Internship Project (Week 3 & 4)

Reads pre-computed results from the data/ folder (generated by
generate_dashboard_data.py) — no model retraining happens here,
so the app stays fast on Streamlit Community Cloud.
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

st.set_page_config(page_title="Sales Forecasting Dashboard", layout="wide")

# ============================================
# Load Data (cached so it only loads once)
# ============================================
@st.cache_data
def load_data():
    clean_sales = pd.read_csv("data/clean_sales.csv", parse_dates=["Order Date"])
    forecasts = pd.read_csv("data/forecasts.csv")
    model_metrics = pd.read_csv("data/model_metrics.csv")
    weekly_anomalies = pd.read_csv("data/weekly_anomalies.csv", parse_dates=["Order Date"])
    clusters = pd.read_csv("data/clusters.csv")
    return clean_sales, forecasts, model_metrics, weekly_anomalies, clusters

clean_sales, forecasts, model_metrics, weekly_anomalies, clusters = load_data()

# ============================================
# Sidebar Navigation
# ============================================
st.sidebar.title("Sales Forecasting System")
page = st.sidebar.radio(
    "Navigate",
    ["Sales Overview", "Forecast Explorer", "Anomaly Report", "Product Demand Segments"]
)

# ============================================
# PAGE 1 — Sales Overview Dashboard
# ============================================
if page == "Sales Overview":
    st.title("Sales Overview Dashboard")

    # --- Interactive filters ---
    col1, col2 = st.columns(2)
    with col1:
        regions = st.multiselect(
            "Filter by Region",
            options=sorted(clean_sales["Region"].unique()),
            default=sorted(clean_sales["Region"].unique())
        )
    with col2:
        categories = st.multiselect(
            "Filter by Category",
            options=sorted(clean_sales["Category"].unique()),
            default=sorted(clean_sales["Category"].unique())
        )

    filtered = clean_sales[
        clean_sales["Region"].isin(regions) & clean_sales["Category"].isin(categories)
    ]

    st.markdown("---")

    # --- Total sales by year ---
    st.subheader("Total Sales by Year")
    yearly = filtered.groupby("Year")["Sales"].sum()
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.bar(yearly.index.astype(str), yearly.values, color="steelblue")
    ax.set_xlabel("Year")
    ax.set_ylabel("Sales")
    st.pyplot(fig)

    # --- Monthly sales trend ---
    st.subheader("Monthly Sales Trend")
    monthly = filtered.groupby(pd.Grouper(key="Order Date", freq="M"))["Sales"].sum()
    fig, ax = plt.subplots(figsize=(10, 4))
    ax.plot(monthly.index, monthly.values, marker="o", linewidth=1.5, color="steelblue")
    ax.set_xlabel("Date")
    ax.set_ylabel("Sales")
    ax.grid(alpha=0.3)
    st.pyplot(fig)

    # --- Sales by region and category ---
    st.subheader("Sales by Region and Category")
    col1, col2 = st.columns(2)
    with col1:
        reg_sales = filtered.groupby("Region")["Sales"].sum().sort_values(ascending=False)
        fig, ax = plt.subplots(figsize=(5, 4))
        ax.bar(reg_sales.index, reg_sales.values, color="skyblue")
        ax.set_ylabel("Sales")
        ax.set_title("Sales by Region")
        st.pyplot(fig)
    with col2:
        cat_sales = filtered.groupby("Category")["Sales"].sum().sort_values(ascending=False)
        fig, ax = plt.subplots(figsize=(5, 4))
        ax.bar(cat_sales.index, cat_sales.values, color=["steelblue", "orange", "green"])
        ax.set_ylabel("Sales")
        ax.set_title("Sales by Category")
        st.pyplot(fig)

# ============================================
# PAGE 2 — Forecast Explorer
# ============================================
elif page == "Forecast Explorer":
    st.title("Forecast Explorer")
    st.caption("Forecasts generated using the best-performing model: XGBoost")

    col1, col2 = st.columns(2)
    with col1:
        forecast_type = st.selectbox("Select View", ["Overall", "Category", "Region"])
    with col2:
        if forecast_type == "Overall":
            segment = "Overall"
        else:
            options = sorted(forecasts[forecasts["Type"] == forecast_type]["Segment"].unique())
            segment = st.selectbox(f"Select {forecast_type}", options)

    horizon = st.slider("Forecast Horizon (months ahead)", min_value=1, max_value=3, value=3)

    segment_forecast = forecasts[forecasts["Segment"] == segment].head(horizon)

    st.subheader(f"{segment} — {horizon}-Month Forecast")
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.bar(segment_forecast["Month"], segment_forecast["Forecast"], color="orange")
    ax.set_xlabel("Month")
    ax.set_ylabel("Forecasted Sales")
    st.pyplot(fig)

    st.dataframe(segment_forecast[["Month", "Forecast"]].reset_index(drop=True), use_container_width=True)

    # --- Model metrics ---
    st.subheader("Model Performance (XGBoost — Best Model)")
    xgb_metrics = model_metrics[model_metrics["Model"] == "XGBoost"].iloc[0]
    col1, col2, col3 = st.columns(3)
    col1.metric("MAE", f"{xgb_metrics['MAE']:.2f}")
    col2.metric("RMSE", f"{xgb_metrics['RMSE']:.2f}")
    col3.metric("MAPE", f"{xgb_metrics['MAPE']:.2f}%")

    with st.expander("Compare all 3 models (SARIMA, Prophet, XGBoost)"):
        st.dataframe(model_metrics, use_container_width=True)

# ============================================
# PAGE 3 — Anomaly Report
# ============================================
elif page == "Anomaly Report":
    st.title("Anomaly Report")
    st.caption("Detected using Isolation Forest on weekly sales")

    fig, ax = plt.subplots(figsize=(10, 4))
    ax.plot(weekly_anomalies["Order Date"], weekly_anomalies["Sales"], label="Weekly Sales", color="steelblue")
    anomalies = weekly_anomalies[weekly_anomalies["Anomaly"] == -1]
    ax.scatter(anomalies["Order Date"], anomalies["Sales"], color="red", label="Anomaly", zorder=5)
    ax.set_xlabel("Date")
    ax.set_ylabel("Sales")
    ax.legend()
    ax.grid(alpha=0.3)
    st.pyplot(fig)

    st.subheader("Detected Anomaly Dates")
    anomaly_table = anomalies[["Order Date", "Sales"]].reset_index(drop=True)
    anomaly_table["Order Date"] = anomaly_table["Order Date"].dt.strftime("%Y-%m-%d")
    st.dataframe(anomaly_table, use_container_width=True)

# ============================================
# PAGE 4 — Product Demand Segments
# ============================================
elif page == "Product Demand Segments":
    st.title("Product Demand Segments")
    st.caption("K-Means clustering (k=3) on sub-category demand features")

    st.subheader("Cluster Visualization (PCA)")
    fig, ax = plt.subplots(figsize=(7, 5))
    scatter = ax.scatter(
        clusters["PC1"], clusters["PC2"],
        c=clusters["Cluster"], cmap="viridis", s=100
    )
    for _, row in clusters.iterrows():
        ax.annotate(row["Sub-Category"], (row["PC1"], row["PC2"]), fontsize=8)
    ax.set_xlabel("Principal Component 1")
    ax.set_ylabel("Principal Component 2")
    st.pyplot(fig)

    st.subheader("Sub-Category to Demand Cluster")
    display_cols = ["Sub-Category", "Cluster_Label", "Total_Sales", "Avg_Order_Value", "Sales_Volatility", "Growth_Rate"]
    st.dataframe(clusters[display_cols].reset_index(drop=True), use_container_width=True)

    st.subheader("Stocking Strategy by Cluster")
    st.markdown("""
    - **Low Volume, Stable Demand** — Maintain moderate inventory, replenish based on demand to avoid holding costs.
    - **High Volume, Stable Demand** — Maintain higher inventory levels; prioritize availability, core revenue drivers.
    - **Growing Demand** — Increase inventory gradually and monitor closely to avoid stockouts as demand rises.
    """)
